// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package bucket

import (
	"context"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/s3"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/s3-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.S3{}
	_ = &svcapitypes.Bucket{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer exit(err)
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.ListBucketsOutput
	resp, err = rm.sdkapi.ListBucketsWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "ListBuckets", err)
	if err != nil {
		if awsErr, ok := ackerr.AWSError(err); ok && awsErr.Code() == "NoSuchBucket" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.Buckets {
		if elem.Name != nil {
			if ko.Spec.Name != nil {
				if *elem.Name != *ko.Spec.Name {
					continue
				}
			}
			ko.Spec.Name = elem.Name
		} else {
			ko.Spec.Name = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	if err := rm.addPutFieldsToSpec(ctx, r, ko); err != nil {
		return nil, err
	}
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return false
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.ListBucketsInput, error) {
	res := &svcsdk.ListBucketsInput{}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer exit(err)
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateBucketOutput
	_ = resp
	resp, err = rm.sdkapi.CreateBucketWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateBucket", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.Location != nil {
		ko.Status.Location = resp.Location
	} else {
		ko.Status.Location = nil
	}

	rm.setStatusDefaults(ko)
	if err := rm.createPutFields(ctx, desired); err != nil {
		return nil, err
	}
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateBucketInput, error) {
	res := &svcsdk.CreateBucketInput{}

	if r.ko.Spec.ACL != nil {
		res.SetACL(*r.ko.Spec.ACL)
	}
	if r.ko.Spec.Name != nil {
		res.SetBucket(*r.ko.Spec.Name)
	}
	if r.ko.Spec.CreateBucketConfiguration != nil {
		f2 := &svcsdk.CreateBucketConfiguration{}
		if r.ko.Spec.CreateBucketConfiguration.LocationConstraint != nil {
			f2.SetLocationConstraint(*r.ko.Spec.CreateBucketConfiguration.LocationConstraint)
		}
		res.SetCreateBucketConfiguration(f2)
	}
	if r.ko.Spec.GrantFullControl != nil {
		res.SetGrantFullControl(*r.ko.Spec.GrantFullControl)
	}
	if r.ko.Spec.GrantRead != nil {
		res.SetGrantRead(*r.ko.Spec.GrantRead)
	}
	if r.ko.Spec.GrantReadACP != nil {
		res.SetGrantReadACP(*r.ko.Spec.GrantReadACP)
	}
	if r.ko.Spec.GrantWrite != nil {
		res.SetGrantWrite(*r.ko.Spec.GrantWrite)
	}
	if r.ko.Spec.GrantWriteACP != nil {
		res.SetGrantWriteACP(*r.ko.Spec.GrantWriteACP)
	}
	if r.ko.Spec.ObjectLockEnabledForBucket != nil {
		res.SetObjectLockEnabledForBucket(*r.ko.Spec.ObjectLockEnabledForBucket)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdateBucket(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer exit(err)
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteBucketOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteBucketWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteBucket", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteBucketInput, error) {
	res := &svcsdk.DeleteBucketInput{}

	if r.ko.Spec.Name != nil {
		res.SetBucket(*r.ko.Spec.Name)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Bucket,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}

	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}

// newAccelerateConfiguration returns a AccelerateConfiguration object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newAccelerateConfiguration(
	r *resource,
) *svcsdk.AccelerateConfiguration {
	res := &svcsdk.AccelerateConfiguration{}

	if r.ko.Spec.Accelerate.Status != nil {
		res.SetStatus(*r.ko.Spec.Accelerate.Status)
	}

	return res
}

// setResourceAccelerate sets the `Accelerate` spec field
// given the output of a `GetBucketAccelerateConfiguration` operation.
func (rm *resourceManager) setResourceAccelerate(
	r *resource,
	resp *svcsdk.GetBucketAccelerateConfigurationOutput,
) *svcapitypes.AccelerateConfiguration {
	res := &svcapitypes.AccelerateConfiguration{}
	if resp.Status != nil {
		res.Status = resp.Status
	}

	return res
}

// newCORSConfiguration returns a CORSConfiguration object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newCORSConfiguration(
	r *resource,
) *svcsdk.CORSConfiguration {
	res := &svcsdk.CORSConfiguration{}

	if r.ko.Spec.CORS.CORSRules != nil {
		resf0 := []*svcsdk.CORSRule{}
		for _, resf0iter := range r.ko.Spec.CORS.CORSRules {
			resf0elem := &svcsdk.CORSRule{}
			if resf0iter.AllowedHeaders != nil {
				resf0elemf0 := []*string{}
				for _, resf0elemf0iter := range resf0iter.AllowedHeaders {
					var resf0elemf0elem string
					resf0elemf0elem = *resf0elemf0iter
					resf0elemf0 = append(resf0elemf0, &resf0elemf0elem)
				}
				resf0elem.SetAllowedHeaders(resf0elemf0)
			}
			if resf0iter.AllowedMethods != nil {
				resf0elemf1 := []*string{}
				for _, resf0elemf1iter := range resf0iter.AllowedMethods {
					var resf0elemf1elem string
					resf0elemf1elem = *resf0elemf1iter
					resf0elemf1 = append(resf0elemf1, &resf0elemf1elem)
				}
				resf0elem.SetAllowedMethods(resf0elemf1)
			}
			if resf0iter.AllowedOrigins != nil {
				resf0elemf2 := []*string{}
				for _, resf0elemf2iter := range resf0iter.AllowedOrigins {
					var resf0elemf2elem string
					resf0elemf2elem = *resf0elemf2iter
					resf0elemf2 = append(resf0elemf2, &resf0elemf2elem)
				}
				resf0elem.SetAllowedOrigins(resf0elemf2)
			}
			if resf0iter.ExposeHeaders != nil {
				resf0elemf3 := []*string{}
				for _, resf0elemf3iter := range resf0iter.ExposeHeaders {
					var resf0elemf3elem string
					resf0elemf3elem = *resf0elemf3iter
					resf0elemf3 = append(resf0elemf3, &resf0elemf3elem)
				}
				resf0elem.SetExposeHeaders(resf0elemf3)
			}
			if resf0iter.MaxAgeSeconds != nil {
				resf0elem.SetMaxAgeSeconds(*resf0iter.MaxAgeSeconds)
			}
			resf0 = append(resf0, resf0elem)
		}
		res.SetCORSRules(resf0)
	}

	return res
}

// setResourceCORS sets the `CORS` spec field
// given the output of a `GetBucketCors` operation.
func (rm *resourceManager) setResourceCORS(
	r *resource,
	resp *svcsdk.GetBucketCorsOutput,
) *svcapitypes.CORSConfiguration {
	res := &svcapitypes.CORSConfiguration{}
	if resp.CORSRules != nil {
		resf0 := []*svcapitypes.CORSRule{}
		for _, resf0iter := range resp.CORSRules {
			resf0elem := &svcapitypes.CORSRule{}
			if resf0iter.AllowedHeaders != nil {
				resf0elemf0 := []*string{}
				for _, resf0elemf0iter := range resf0iter.AllowedHeaders {
					var resf0elemf0elem string
					resf0elemf0elem = *resf0elemf0iter
					resf0elemf0 = append(resf0elemf0, &resf0elemf0elem)
				}
				resf0elem.AllowedHeaders = resf0elemf0
			}
			if resf0iter.AllowedMethods != nil {
				resf0elemf1 := []*string{}
				for _, resf0elemf1iter := range resf0iter.AllowedMethods {
					var resf0elemf1elem string
					resf0elemf1elem = *resf0elemf1iter
					resf0elemf1 = append(resf0elemf1, &resf0elemf1elem)
				}
				resf0elem.AllowedMethods = resf0elemf1
			}
			if resf0iter.AllowedOrigins != nil {
				resf0elemf2 := []*string{}
				for _, resf0elemf2iter := range resf0iter.AllowedOrigins {
					var resf0elemf2elem string
					resf0elemf2elem = *resf0elemf2iter
					resf0elemf2 = append(resf0elemf2, &resf0elemf2elem)
				}
				resf0elem.AllowedOrigins = resf0elemf2
			}
			if resf0iter.ExposeHeaders != nil {
				resf0elemf3 := []*string{}
				for _, resf0elemf3iter := range resf0iter.ExposeHeaders {
					var resf0elemf3elem string
					resf0elemf3elem = *resf0elemf3iter
					resf0elemf3 = append(resf0elemf3, &resf0elemf3elem)
				}
				resf0elem.ExposeHeaders = resf0elemf3
			}
			if resf0iter.MaxAgeSeconds != nil {
				resf0elem.MaxAgeSeconds = resf0iter.MaxAgeSeconds
			}
			resf0 = append(resf0, resf0elem)
		}
		res.CORSRules = resf0
	}

	return res
}

// newServerSideEncryptionConfiguration returns a ServerSideEncryptionConfiguration object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newServerSideEncryptionConfiguration(
	r *resource,
) *svcsdk.ServerSideEncryptionConfiguration {
	res := &svcsdk.ServerSideEncryptionConfiguration{}

	if r.ko.Spec.Encryption.Rules != nil {
		resf0 := []*svcsdk.ServerSideEncryptionRule{}
		for _, resf0iter := range r.ko.Spec.Encryption.Rules {
			resf0elem := &svcsdk.ServerSideEncryptionRule{}
			if resf0iter.ApplyServerSideEncryptionByDefault != nil {
				resf0elemf0 := &svcsdk.ServerSideEncryptionByDefault{}
				if resf0iter.ApplyServerSideEncryptionByDefault.KMSMasterKeyID != nil {
					resf0elemf0.SetKMSMasterKeyID(*resf0iter.ApplyServerSideEncryptionByDefault.KMSMasterKeyID)
				}
				if resf0iter.ApplyServerSideEncryptionByDefault.SSEAlgorithm != nil {
					resf0elemf0.SetSSEAlgorithm(*resf0iter.ApplyServerSideEncryptionByDefault.SSEAlgorithm)
				}
				resf0elem.SetApplyServerSideEncryptionByDefault(resf0elemf0)
			}
			if resf0iter.BucketKeyEnabled != nil {
				resf0elem.SetBucketKeyEnabled(*resf0iter.BucketKeyEnabled)
			}
			resf0 = append(resf0, resf0elem)
		}
		res.SetRules(resf0)
	}

	return res
}

// setResourceEncryption sets the `Encryption` spec field
// given the output of a `GetBucketEncryption` operation.
func (rm *resourceManager) setResourceEncryption(
	r *resource,
	resp *svcsdk.GetBucketEncryptionOutput,
) *svcapitypes.ServerSideEncryptionConfiguration {
	res := &svcapitypes.ServerSideEncryptionConfiguration{}
	if resp.ServerSideEncryptionConfiguration.Rules != nil {
		resf0 := []*svcapitypes.ServerSideEncryptionRule{}
		for _, resf0iter := range resp.ServerSideEncryptionConfiguration.Rules {
			resf0elem := &svcapitypes.ServerSideEncryptionRule{}
			if resf0iter.ApplyServerSideEncryptionByDefault != nil {
				resf0elemf0 := &svcapitypes.ServerSideEncryptionByDefault{}
				if resf0iter.ApplyServerSideEncryptionByDefault.KMSMasterKeyID != nil {
					resf0elemf0.KMSMasterKeyID = resf0iter.ApplyServerSideEncryptionByDefault.KMSMasterKeyID
				}
				if resf0iter.ApplyServerSideEncryptionByDefault.SSEAlgorithm != nil {
					resf0elemf0.SSEAlgorithm = resf0iter.ApplyServerSideEncryptionByDefault.SSEAlgorithm
				}
				resf0elem.ApplyServerSideEncryptionByDefault = resf0elemf0
			}
			if resf0iter.BucketKeyEnabled != nil {
				resf0elem.BucketKeyEnabled = resf0iter.BucketKeyEnabled
			}
			resf0 = append(resf0, resf0elem)
		}
		res.Rules = resf0
	}

	return res
}

// newLifecycleConfiguration returns a LifecycleConfiguration object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newLifecycleConfiguration(
	r *resource,
) *svcsdk.BucketLifecycleConfiguration {
	res := &svcsdk.BucketLifecycleConfiguration{}

	if r.ko.Spec.Lifecycle.Rules != nil {
		resf0 := []*svcsdk.LifecycleRule{}
		for _, resf0iter := range r.ko.Spec.Lifecycle.Rules {
			resf0elem := &svcsdk.LifecycleRule{}
			if resf0iter.AbortIncompleteMultipartUpload != nil {
				resf0elemf0 := &svcsdk.AbortIncompleteMultipartUpload{}
				if resf0iter.AbortIncompleteMultipartUpload.DaysAfterInitiation != nil {
					resf0elemf0.SetDaysAfterInitiation(*resf0iter.AbortIncompleteMultipartUpload.DaysAfterInitiation)
				}
				resf0elem.SetAbortIncompleteMultipartUpload(resf0elemf0)
			}
			if resf0iter.Expiration != nil {
				resf0elemf1 := &svcsdk.LifecycleExpiration{}
				if resf0iter.Expiration.Date != nil {
					resf0elemf1.SetDate(resf0iter.Expiration.Date.Time)
				}
				if resf0iter.Expiration.Days != nil {
					resf0elemf1.SetDays(*resf0iter.Expiration.Days)
				}
				if resf0iter.Expiration.ExpiredObjectDeleteMarker != nil {
					resf0elemf1.SetExpiredObjectDeleteMarker(*resf0iter.Expiration.ExpiredObjectDeleteMarker)
				}
				resf0elem.SetExpiration(resf0elemf1)
			}
			if resf0iter.Filter != nil {
				resf0elemf2 := &svcsdk.LifecycleRuleFilter{}
				if resf0iter.Filter.And != nil {
					resf0elemf2f0 := &svcsdk.LifecycleRuleAndOperator{}
					if resf0iter.Filter.And.Prefix != nil {
						resf0elemf2f0.SetPrefix(*resf0iter.Filter.And.Prefix)
					}
					if resf0iter.Filter.And.Tags != nil {
						resf0elemf2f0f1 := []*svcsdk.Tag{}
						for _, resf0elemf2f0f1iter := range resf0iter.Filter.And.Tags {
							resf0elemf2f0f1elem := &svcsdk.Tag{}
							if resf0elemf2f0f1iter.Key != nil {
								resf0elemf2f0f1elem.SetKey(*resf0elemf2f0f1iter.Key)
							}
							if resf0elemf2f0f1iter.Value != nil {
								resf0elemf2f0f1elem.SetValue(*resf0elemf2f0f1iter.Value)
							}
							resf0elemf2f0f1 = append(resf0elemf2f0f1, resf0elemf2f0f1elem)
						}
						resf0elemf2f0.SetTags(resf0elemf2f0f1)
					}
					resf0elemf2.SetAnd(resf0elemf2f0)
				}
				if resf0iter.Filter.Prefix != nil {
					resf0elemf2.SetPrefix(*resf0iter.Filter.Prefix)
				}
				if resf0iter.Filter.Tag != nil {
					resf0elemf2f2 := &svcsdk.Tag{}
					if resf0iter.Filter.Tag.Key != nil {
						resf0elemf2f2.SetKey(*resf0iter.Filter.Tag.Key)
					}
					if resf0iter.Filter.Tag.Value != nil {
						resf0elemf2f2.SetValue(*resf0iter.Filter.Tag.Value)
					}
					resf0elemf2.SetTag(resf0elemf2f2)
				}
				resf0elem.SetFilter(resf0elemf2)
			}
			if resf0iter.ID != nil {
				resf0elem.SetID(*resf0iter.ID)
			}
			if resf0iter.NoncurrentVersionExpiration != nil {
				resf0elemf4 := &svcsdk.NoncurrentVersionExpiration{}
				if resf0iter.NoncurrentVersionExpiration.NoncurrentDays != nil {
					resf0elemf4.SetNoncurrentDays(*resf0iter.NoncurrentVersionExpiration.NoncurrentDays)
				}
				resf0elem.SetNoncurrentVersionExpiration(resf0elemf4)
			}
			if resf0iter.NoncurrentVersionTransitions != nil {
				resf0elemf5 := []*svcsdk.NoncurrentVersionTransition{}
				for _, resf0elemf5iter := range resf0iter.NoncurrentVersionTransitions {
					resf0elemf5elem := &svcsdk.NoncurrentVersionTransition{}
					if resf0elemf5iter.NoncurrentDays != nil {
						resf0elemf5elem.SetNoncurrentDays(*resf0elemf5iter.NoncurrentDays)
					}
					if resf0elemf5iter.StorageClass != nil {
						resf0elemf5elem.SetStorageClass(*resf0elemf5iter.StorageClass)
					}
					resf0elemf5 = append(resf0elemf5, resf0elemf5elem)
				}
				resf0elem.SetNoncurrentVersionTransitions(resf0elemf5)
			}
			if resf0iter.Prefix != nil {
				resf0elem.SetPrefix(*resf0iter.Prefix)
			}
			if resf0iter.Status != nil {
				resf0elem.SetStatus(*resf0iter.Status)
			}
			if resf0iter.Transitions != nil {
				resf0elemf8 := []*svcsdk.Transition{}
				for _, resf0elemf8iter := range resf0iter.Transitions {
					resf0elemf8elem := &svcsdk.Transition{}
					if resf0elemf8iter.Date != nil {
						resf0elemf8elem.SetDate(resf0elemf8iter.Date.Time)
					}
					if resf0elemf8iter.Days != nil {
						resf0elemf8elem.SetDays(*resf0elemf8iter.Days)
					}
					if resf0elemf8iter.StorageClass != nil {
						resf0elemf8elem.SetStorageClass(*resf0elemf8iter.StorageClass)
					}
					resf0elemf8 = append(resf0elemf8, resf0elemf8elem)
				}
				resf0elem.SetTransitions(resf0elemf8)
			}
			resf0 = append(resf0, resf0elem)
		}
		res.SetRules(resf0)
	}

	return res
}

// setResourceLifecycle sets the `Lifecycle` spec field
// given the output of a `GetBucketLifecycleConfiguration` operation.
func (rm *resourceManager) setResourceLifecycle(
	r *resource,
	resp *svcsdk.GetBucketLifecycleConfigurationOutput,
) *svcapitypes.BucketLifecycleConfiguration {
	res := &svcapitypes.BucketLifecycleConfiguration{}
	if resp.Rules != nil {
		resf0 := []*svcapitypes.LifecycleRule{}
		for _, resf0iter := range resp.Rules {
			resf0elem := &svcapitypes.LifecycleRule{}
			if resf0iter.AbortIncompleteMultipartUpload != nil {
				resf0elemf0 := &svcapitypes.AbortIncompleteMultipartUpload{}
				if resf0iter.AbortIncompleteMultipartUpload.DaysAfterInitiation != nil {
					resf0elemf0.DaysAfterInitiation = resf0iter.AbortIncompleteMultipartUpload.DaysAfterInitiation
				}
				resf0elem.AbortIncompleteMultipartUpload = resf0elemf0
			}
			if resf0iter.Expiration != nil {
				resf0elemf1 := &svcapitypes.LifecycleExpiration{}
				if resf0iter.Expiration.Date != nil {
					resf0elemf1.Date = &metav1.Time{*resf0iter.Expiration.Date}
				}
				if resf0iter.Expiration.Days != nil {
					resf0elemf1.Days = resf0iter.Expiration.Days
				}
				if resf0iter.Expiration.ExpiredObjectDeleteMarker != nil {
					resf0elemf1.ExpiredObjectDeleteMarker = resf0iter.Expiration.ExpiredObjectDeleteMarker
				}
				resf0elem.Expiration = resf0elemf1
			}
			if resf0iter.Filter != nil {
				resf0elemf2 := &svcapitypes.LifecycleRuleFilter{}
				if resf0iter.Filter.And != nil {
					resf0elemf2f0 := &svcapitypes.LifecycleRuleAndOperator{}
					if resf0iter.Filter.And.Prefix != nil {
						resf0elemf2f0.Prefix = resf0iter.Filter.And.Prefix
					}
					if resf0iter.Filter.And.Tags != nil {
						resf0elemf2f0f1 := []*svcapitypes.Tag{}
						for _, resf0elemf2f0f1iter := range resf0iter.Filter.And.Tags {
							resf0elemf2f0f1elem := &svcapitypes.Tag{}
							if resf0elemf2f0f1iter.Key != nil {
								resf0elemf2f0f1elem.Key = resf0elemf2f0f1iter.Key
							}
							if resf0elemf2f0f1iter.Value != nil {
								resf0elemf2f0f1elem.Value = resf0elemf2f0f1iter.Value
							}
							resf0elemf2f0f1 = append(resf0elemf2f0f1, resf0elemf2f0f1elem)
						}
						resf0elemf2f0.Tags = resf0elemf2f0f1
					}
					resf0elemf2.And = resf0elemf2f0
				}
				if resf0iter.Filter.Prefix != nil {
					resf0elemf2.Prefix = resf0iter.Filter.Prefix
				}
				if resf0iter.Filter.Tag != nil {
					resf0elemf2f2 := &svcapitypes.Tag{}
					if resf0iter.Filter.Tag.Key != nil {
						resf0elemf2f2.Key = resf0iter.Filter.Tag.Key
					}
					if resf0iter.Filter.Tag.Value != nil {
						resf0elemf2f2.Value = resf0iter.Filter.Tag.Value
					}
					resf0elemf2.Tag = resf0elemf2f2
				}
				resf0elem.Filter = resf0elemf2
			}
			if resf0iter.ID != nil {
				resf0elem.ID = resf0iter.ID
			}
			if resf0iter.NoncurrentVersionExpiration != nil {
				resf0elemf4 := &svcapitypes.NoncurrentVersionExpiration{}
				if resf0iter.NoncurrentVersionExpiration.NoncurrentDays != nil {
					resf0elemf4.NoncurrentDays = resf0iter.NoncurrentVersionExpiration.NoncurrentDays
				}
				resf0elem.NoncurrentVersionExpiration = resf0elemf4
			}
			if resf0iter.NoncurrentVersionTransitions != nil {
				resf0elemf5 := []*svcapitypes.NoncurrentVersionTransition{}
				for _, resf0elemf5iter := range resf0iter.NoncurrentVersionTransitions {
					resf0elemf5elem := &svcapitypes.NoncurrentVersionTransition{}
					if resf0elemf5iter.NoncurrentDays != nil {
						resf0elemf5elem.NoncurrentDays = resf0elemf5iter.NoncurrentDays
					}
					if resf0elemf5iter.StorageClass != nil {
						resf0elemf5elem.StorageClass = resf0elemf5iter.StorageClass
					}
					resf0elemf5 = append(resf0elemf5, resf0elemf5elem)
				}
				resf0elem.NoncurrentVersionTransitions = resf0elemf5
			}
			if resf0iter.Prefix != nil {
				resf0elem.Prefix = resf0iter.Prefix
			}
			if resf0iter.Status != nil {
				resf0elem.Status = resf0iter.Status
			}
			if resf0iter.Transitions != nil {
				resf0elemf8 := []*svcapitypes.Transition{}
				for _, resf0elemf8iter := range resf0iter.Transitions {
					resf0elemf8elem := &svcapitypes.Transition{}
					if resf0elemf8iter.Date != nil {
						resf0elemf8elem.Date = &metav1.Time{*resf0elemf8iter.Date}
					}
					if resf0elemf8iter.Days != nil {
						resf0elemf8elem.Days = resf0elemf8iter.Days
					}
					if resf0elemf8iter.StorageClass != nil {
						resf0elemf8elem.StorageClass = resf0elemf8iter.StorageClass
					}
					resf0elemf8 = append(resf0elemf8, resf0elemf8elem)
				}
				resf0elem.Transitions = resf0elemf8
			}
			resf0 = append(resf0, resf0elem)
		}
		res.Rules = resf0
	}

	return res
}

// newBucketLoggingStatus returns a BucketLoggingStatus object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newBucketLoggingStatus(
	r *resource,
) *svcsdk.BucketLoggingStatus {
	res := &svcsdk.BucketLoggingStatus{}

	if r.ko.Spec.Logging.LoggingEnabled != nil {
		resf0 := &svcsdk.LoggingEnabled{}
		if r.ko.Spec.Logging.LoggingEnabled.TargetBucket != nil {
			resf0.SetTargetBucket(*r.ko.Spec.Logging.LoggingEnabled.TargetBucket)
		}
		if r.ko.Spec.Logging.LoggingEnabled.TargetGrants != nil {
			resf0f1 := []*svcsdk.TargetGrant{}
			for _, resf0f1iter := range r.ko.Spec.Logging.LoggingEnabled.TargetGrants {
				resf0f1elem := &svcsdk.TargetGrant{}
				if resf0f1iter.Grantee != nil {
					resf0f1elemf0 := &svcsdk.Grantee{}
					if resf0f1iter.Grantee.DisplayName != nil {
						resf0f1elemf0.SetDisplayName(*resf0f1iter.Grantee.DisplayName)
					}
					if resf0f1iter.Grantee.EmailAddress != nil {
						resf0f1elemf0.SetEmailAddress(*resf0f1iter.Grantee.EmailAddress)
					}
					if resf0f1iter.Grantee.ID != nil {
						resf0f1elemf0.SetID(*resf0f1iter.Grantee.ID)
					}
					if resf0f1iter.Grantee.Type != nil {
						resf0f1elemf0.SetType(*resf0f1iter.Grantee.Type)
					}
					if resf0f1iter.Grantee.URI != nil {
						resf0f1elemf0.SetURI(*resf0f1iter.Grantee.URI)
					}
					resf0f1elem.SetGrantee(resf0f1elemf0)
				}
				if resf0f1iter.Permission != nil {
					resf0f1elem.SetPermission(*resf0f1iter.Permission)
				}
				resf0f1 = append(resf0f1, resf0f1elem)
			}
			resf0.SetTargetGrants(resf0f1)
		}
		if r.ko.Spec.Logging.LoggingEnabled.TargetPrefix != nil {
			resf0.SetTargetPrefix(*r.ko.Spec.Logging.LoggingEnabled.TargetPrefix)
		}
		res.SetLoggingEnabled(resf0)
	}

	return res
}

// setResourceLogging sets the `Logging` spec field
// given the output of a `GetBucketLogging` operation.
func (rm *resourceManager) setResourceLogging(
	r *resource,
	resp *svcsdk.GetBucketLoggingOutput,
) *svcapitypes.BucketLoggingStatus {
	res := &svcapitypes.BucketLoggingStatus{}
	if resp.LoggingEnabled != nil {
		resf0 := &svcapitypes.LoggingEnabled{}
		if resp.LoggingEnabled.TargetBucket != nil {
			resf0.TargetBucket = resp.LoggingEnabled.TargetBucket
		}
		if resp.LoggingEnabled.TargetGrants != nil {
			resf0f1 := []*svcapitypes.TargetGrant{}
			for _, resf0f1iter := range resp.LoggingEnabled.TargetGrants {
				resf0f1elem := &svcapitypes.TargetGrant{}
				if resf0f1iter.Grantee != nil {
					resf0f1elemf0 := &svcapitypes.Grantee{}
					if resf0f1iter.Grantee.DisplayName != nil {
						resf0f1elemf0.DisplayName = resf0f1iter.Grantee.DisplayName
					}
					if resf0f1iter.Grantee.EmailAddress != nil {
						resf0f1elemf0.EmailAddress = resf0f1iter.Grantee.EmailAddress
					}
					if resf0f1iter.Grantee.ID != nil {
						resf0f1elemf0.ID = resf0f1iter.Grantee.ID
					}
					if resf0f1iter.Grantee.Type != nil {
						resf0f1elemf0.Type = resf0f1iter.Grantee.Type
					}
					if resf0f1iter.Grantee.URI != nil {
						resf0f1elemf0.URI = resf0f1iter.Grantee.URI
					}
					resf0f1elem.Grantee = resf0f1elemf0
				}
				if resf0f1iter.Permission != nil {
					resf0f1elem.Permission = resf0f1iter.Permission
				}
				resf0f1 = append(resf0f1, resf0f1elem)
			}
			resf0.TargetGrants = resf0f1
		}
		if resp.LoggingEnabled.TargetPrefix != nil {
			resf0.TargetPrefix = resp.LoggingEnabled.TargetPrefix
		}
		res.LoggingEnabled = resf0
	}

	return res
}

// newNotificationConfiguration returns a NotificationConfiguration object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newNotificationConfiguration(
	r *resource,
) *svcsdk.NotificationConfiguration {
	res := &svcsdk.NotificationConfiguration{}

	if r.ko.Spec.Notification.LambdaFunctionConfigurations != nil {
		resf0 := []*svcsdk.LambdaFunctionConfiguration{}
		for _, resf0iter := range r.ko.Spec.Notification.LambdaFunctionConfigurations {
			resf0elem := &svcsdk.LambdaFunctionConfiguration{}
			if resf0iter.Events != nil {
				resf0elemf0 := []*string{}
				for _, resf0elemf0iter := range resf0iter.Events {
					var resf0elemf0elem string
					resf0elemf0elem = *resf0elemf0iter
					resf0elemf0 = append(resf0elemf0, &resf0elemf0elem)
				}
				resf0elem.SetEvents(resf0elemf0)
			}
			if resf0iter.Filter != nil {
				resf0elemf1 := &svcsdk.NotificationConfigurationFilter{}
				if resf0iter.Filter.Key != nil {
					resf0elemf1f0 := &svcsdk.KeyFilter{}
					if resf0iter.Filter.Key.FilterRules != nil {
						resf0elemf1f0f0 := []*svcsdk.FilterRule{}
						for _, resf0elemf1f0f0iter := range resf0iter.Filter.Key.FilterRules {
							resf0elemf1f0f0elem := &svcsdk.FilterRule{}
							if resf0elemf1f0f0iter.Name != nil {
								resf0elemf1f0f0elem.SetName(*resf0elemf1f0f0iter.Name)
							}
							if resf0elemf1f0f0iter.Value != nil {
								resf0elemf1f0f0elem.SetValue(*resf0elemf1f0f0iter.Value)
							}
							resf0elemf1f0f0 = append(resf0elemf1f0f0, resf0elemf1f0f0elem)
						}
						resf0elemf1f0.SetFilterRules(resf0elemf1f0f0)
					}
					resf0elemf1.SetKey(resf0elemf1f0)
				}
				resf0elem.SetFilter(resf0elemf1)
			}
			if resf0iter.ID != nil {
				resf0elem.SetId(*resf0iter.ID)
			}
			if resf0iter.LambdaFunctionARN != nil {
				resf0elem.SetLambdaFunctionArn(*resf0iter.LambdaFunctionARN)
			}
			resf0 = append(resf0, resf0elem)
		}
		res.SetLambdaFunctionConfigurations(resf0)
	}
	if r.ko.Spec.Notification.QueueConfigurations != nil {
		resf1 := []*svcsdk.QueueConfiguration{}
		for _, resf1iter := range r.ko.Spec.Notification.QueueConfigurations {
			resf1elem := &svcsdk.QueueConfiguration{}
			if resf1iter.Events != nil {
				resf1elemf0 := []*string{}
				for _, resf1elemf0iter := range resf1iter.Events {
					var resf1elemf0elem string
					resf1elemf0elem = *resf1elemf0iter
					resf1elemf0 = append(resf1elemf0, &resf1elemf0elem)
				}
				resf1elem.SetEvents(resf1elemf0)
			}
			if resf1iter.Filter != nil {
				resf1elemf1 := &svcsdk.NotificationConfigurationFilter{}
				if resf1iter.Filter.Key != nil {
					resf1elemf1f0 := &svcsdk.KeyFilter{}
					if resf1iter.Filter.Key.FilterRules != nil {
						resf1elemf1f0f0 := []*svcsdk.FilterRule{}
						for _, resf1elemf1f0f0iter := range resf1iter.Filter.Key.FilterRules {
							resf1elemf1f0f0elem := &svcsdk.FilterRule{}
							if resf1elemf1f0f0iter.Name != nil {
								resf1elemf1f0f0elem.SetName(*resf1elemf1f0f0iter.Name)
							}
							if resf1elemf1f0f0iter.Value != nil {
								resf1elemf1f0f0elem.SetValue(*resf1elemf1f0f0iter.Value)
							}
							resf1elemf1f0f0 = append(resf1elemf1f0f0, resf1elemf1f0f0elem)
						}
						resf1elemf1f0.SetFilterRules(resf1elemf1f0f0)
					}
					resf1elemf1.SetKey(resf1elemf1f0)
				}
				resf1elem.SetFilter(resf1elemf1)
			}
			if resf1iter.ID != nil {
				resf1elem.SetId(*resf1iter.ID)
			}
			if resf1iter.QueueARN != nil {
				resf1elem.SetQueueArn(*resf1iter.QueueARN)
			}
			resf1 = append(resf1, resf1elem)
		}
		res.SetQueueConfigurations(resf1)
	}
	if r.ko.Spec.Notification.TopicConfigurations != nil {
		resf2 := []*svcsdk.TopicConfiguration{}
		for _, resf2iter := range r.ko.Spec.Notification.TopicConfigurations {
			resf2elem := &svcsdk.TopicConfiguration{}
			if resf2iter.Events != nil {
				resf2elemf0 := []*string{}
				for _, resf2elemf0iter := range resf2iter.Events {
					var resf2elemf0elem string
					resf2elemf0elem = *resf2elemf0iter
					resf2elemf0 = append(resf2elemf0, &resf2elemf0elem)
				}
				resf2elem.SetEvents(resf2elemf0)
			}
			if resf2iter.Filter != nil {
				resf2elemf1 := &svcsdk.NotificationConfigurationFilter{}
				if resf2iter.Filter.Key != nil {
					resf2elemf1f0 := &svcsdk.KeyFilter{}
					if resf2iter.Filter.Key.FilterRules != nil {
						resf2elemf1f0f0 := []*svcsdk.FilterRule{}
						for _, resf2elemf1f0f0iter := range resf2iter.Filter.Key.FilterRules {
							resf2elemf1f0f0elem := &svcsdk.FilterRule{}
							if resf2elemf1f0f0iter.Name != nil {
								resf2elemf1f0f0elem.SetName(*resf2elemf1f0f0iter.Name)
							}
							if resf2elemf1f0f0iter.Value != nil {
								resf2elemf1f0f0elem.SetValue(*resf2elemf1f0f0iter.Value)
							}
							resf2elemf1f0f0 = append(resf2elemf1f0f0, resf2elemf1f0f0elem)
						}
						resf2elemf1f0.SetFilterRules(resf2elemf1f0f0)
					}
					resf2elemf1.SetKey(resf2elemf1f0)
				}
				resf2elem.SetFilter(resf2elemf1)
			}
			if resf2iter.ID != nil {
				resf2elem.SetId(*resf2iter.ID)
			}
			if resf2iter.TopicARN != nil {
				resf2elem.SetTopicArn(*resf2iter.TopicARN)
			}
			resf2 = append(resf2, resf2elem)
		}
		res.SetTopicConfigurations(resf2)
	}

	return res
}

// setResourceNotification sets the `Notification` spec field
// given the output of a `GetBucketNotificationConfiguration` operation.
func (rm *resourceManager) setResourceNotification(
	r *resource,
	resp *svcsdk.NotificationConfiguration,
) *svcapitypes.NotificationConfiguration {
	res := &svcapitypes.NotificationConfiguration{}
	if resp.LambdaFunctionConfigurations != nil {
		resf0 := []*svcapitypes.LambdaFunctionConfiguration{}
		for _, resf0iter := range resp.LambdaFunctionConfigurations {
			resf0elem := &svcapitypes.LambdaFunctionConfiguration{}
			if resf0iter.Events != nil {
				resf0elemf0 := []*string{}
				for _, resf0elemf0iter := range resf0iter.Events {
					var resf0elemf0elem string
					resf0elemf0elem = *resf0elemf0iter
					resf0elemf0 = append(resf0elemf0, &resf0elemf0elem)
				}
				resf0elem.Events = resf0elemf0
			}
			if resf0iter.Filter != nil {
				resf0elemf1 := &svcapitypes.NotificationConfigurationFilter{}
				if resf0iter.Filter.Key != nil {
					resf0elemf1f0 := &svcapitypes.KeyFilter{}
					if resf0iter.Filter.Key.FilterRules != nil {
						resf0elemf1f0f0 := []*svcapitypes.FilterRule{}
						for _, resf0elemf1f0f0iter := range resf0iter.Filter.Key.FilterRules {
							resf0elemf1f0f0elem := &svcapitypes.FilterRule{}
							if resf0elemf1f0f0iter.Name != nil {
								resf0elemf1f0f0elem.Name = resf0elemf1f0f0iter.Name
							}
							if resf0elemf1f0f0iter.Value != nil {
								resf0elemf1f0f0elem.Value = resf0elemf1f0f0iter.Value
							}
							resf0elemf1f0f0 = append(resf0elemf1f0f0, resf0elemf1f0f0elem)
						}
						resf0elemf1f0.FilterRules = resf0elemf1f0f0
					}
					resf0elemf1.Key = resf0elemf1f0
				}
				resf0elem.Filter = resf0elemf1
			}
			if resf0iter.Id != nil {
				resf0elem.ID = resf0iter.Id
			}
			if resf0iter.LambdaFunctionArn != nil {
				resf0elem.LambdaFunctionARN = resf0iter.LambdaFunctionArn
			}
			resf0 = append(resf0, resf0elem)
		}
		res.LambdaFunctionConfigurations = resf0
	}
	if resp.QueueConfigurations != nil {
		resf1 := []*svcapitypes.QueueConfiguration{}
		for _, resf1iter := range resp.QueueConfigurations {
			resf1elem := &svcapitypes.QueueConfiguration{}
			if resf1iter.Events != nil {
				resf1elemf0 := []*string{}
				for _, resf1elemf0iter := range resf1iter.Events {
					var resf1elemf0elem string
					resf1elemf0elem = *resf1elemf0iter
					resf1elemf0 = append(resf1elemf0, &resf1elemf0elem)
				}
				resf1elem.Events = resf1elemf0
			}
			if resf1iter.Filter != nil {
				resf1elemf1 := &svcapitypes.NotificationConfigurationFilter{}
				if resf1iter.Filter.Key != nil {
					resf1elemf1f0 := &svcapitypes.KeyFilter{}
					if resf1iter.Filter.Key.FilterRules != nil {
						resf1elemf1f0f0 := []*svcapitypes.FilterRule{}
						for _, resf1elemf1f0f0iter := range resf1iter.Filter.Key.FilterRules {
							resf1elemf1f0f0elem := &svcapitypes.FilterRule{}
							if resf1elemf1f0f0iter.Name != nil {
								resf1elemf1f0f0elem.Name = resf1elemf1f0f0iter.Name
							}
							if resf1elemf1f0f0iter.Value != nil {
								resf1elemf1f0f0elem.Value = resf1elemf1f0f0iter.Value
							}
							resf1elemf1f0f0 = append(resf1elemf1f0f0, resf1elemf1f0f0elem)
						}
						resf1elemf1f0.FilterRules = resf1elemf1f0f0
					}
					resf1elemf1.Key = resf1elemf1f0
				}
				resf1elem.Filter = resf1elemf1
			}
			if resf1iter.Id != nil {
				resf1elem.ID = resf1iter.Id
			}
			if resf1iter.QueueArn != nil {
				resf1elem.QueueARN = resf1iter.QueueArn
			}
			resf1 = append(resf1, resf1elem)
		}
		res.QueueConfigurations = resf1
	}
	if resp.TopicConfigurations != nil {
		resf2 := []*svcapitypes.TopicConfiguration{}
		for _, resf2iter := range resp.TopicConfigurations {
			resf2elem := &svcapitypes.TopicConfiguration{}
			if resf2iter.Events != nil {
				resf2elemf0 := []*string{}
				for _, resf2elemf0iter := range resf2iter.Events {
					var resf2elemf0elem string
					resf2elemf0elem = *resf2elemf0iter
					resf2elemf0 = append(resf2elemf0, &resf2elemf0elem)
				}
				resf2elem.Events = resf2elemf0
			}
			if resf2iter.Filter != nil {
				resf2elemf1 := &svcapitypes.NotificationConfigurationFilter{}
				if resf2iter.Filter.Key != nil {
					resf2elemf1f0 := &svcapitypes.KeyFilter{}
					if resf2iter.Filter.Key.FilterRules != nil {
						resf2elemf1f0f0 := []*svcapitypes.FilterRule{}
						for _, resf2elemf1f0f0iter := range resf2iter.Filter.Key.FilterRules {
							resf2elemf1f0f0elem := &svcapitypes.FilterRule{}
							if resf2elemf1f0f0iter.Name != nil {
								resf2elemf1f0f0elem.Name = resf2elemf1f0f0iter.Name
							}
							if resf2elemf1f0f0iter.Value != nil {
								resf2elemf1f0f0elem.Value = resf2elemf1f0f0iter.Value
							}
							resf2elemf1f0f0 = append(resf2elemf1f0f0, resf2elemf1f0f0elem)
						}
						resf2elemf1f0.FilterRules = resf2elemf1f0f0
					}
					resf2elemf1.Key = resf2elemf1f0
				}
				resf2elem.Filter = resf2elemf1
			}
			if resf2iter.Id != nil {
				resf2elem.ID = resf2iter.Id
			}
			if resf2iter.TopicArn != nil {
				resf2elem.TopicARN = resf2iter.TopicArn
			}
			resf2 = append(resf2, resf2elem)
		}
		res.TopicConfigurations = resf2
	}

	return res
}

// newOwnershipControls returns a OwnershipControls object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newOwnershipControls(
	r *resource,
) *svcsdk.OwnershipControls {
	res := &svcsdk.OwnershipControls{}

	if r.ko.Spec.OwnershipControls.Rules != nil {
		resf0 := []*svcsdk.OwnershipControlsRule{}
		for _, resf0iter := range r.ko.Spec.OwnershipControls.Rules {
			resf0elem := &svcsdk.OwnershipControlsRule{}
			if resf0iter.ObjectOwnership != nil {
				resf0elem.SetObjectOwnership(*resf0iter.ObjectOwnership)
			}
			resf0 = append(resf0, resf0elem)
		}
		res.SetRules(resf0)
	}

	return res
}

// setResourceOwnershipControls sets the `OwnershipControls` spec field
// given the output of a `GetBucketOwnershipControls` operation.
func (rm *resourceManager) setResourceOwnershipControls(
	r *resource,
	resp *svcsdk.GetBucketOwnershipControlsOutput,
) *svcapitypes.OwnershipControls {
	res := &svcapitypes.OwnershipControls{}
	if resp.OwnershipControls.Rules != nil {
		resf0 := []*svcapitypes.OwnershipControlsRule{}
		for _, resf0iter := range resp.OwnershipControls.Rules {
			resf0elem := &svcapitypes.OwnershipControlsRule{}
			if resf0iter.ObjectOwnership != nil {
				resf0elem.ObjectOwnership = resf0iter.ObjectOwnership
			}
			resf0 = append(resf0, resf0elem)
		}
		res.Rules = resf0
	}

	return res
}

// newReplicationConfiguration returns a ReplicationConfiguration object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newReplicationConfiguration(
	r *resource,
) *svcsdk.ReplicationConfiguration {
	res := &svcsdk.ReplicationConfiguration{}

	if r.ko.Spec.Replication.Role != nil {
		res.SetRole(*r.ko.Spec.Replication.Role)
	}
	if r.ko.Spec.Replication.Rules != nil {
		resf1 := []*svcsdk.ReplicationRule{}
		for _, resf1iter := range r.ko.Spec.Replication.Rules {
			resf1elem := &svcsdk.ReplicationRule{}
			if resf1iter.DeleteMarkerReplication != nil {
				resf1elemf0 := &svcsdk.DeleteMarkerReplication{}
				if resf1iter.DeleteMarkerReplication.Status != nil {
					resf1elemf0.SetStatus(*resf1iter.DeleteMarkerReplication.Status)
				}
				resf1elem.SetDeleteMarkerReplication(resf1elemf0)
			}
			if resf1iter.Destination != nil {
				resf1elemf1 := &svcsdk.Destination{}
				if resf1iter.Destination.AccessControlTranslation != nil {
					resf1elemf1f0 := &svcsdk.AccessControlTranslation{}
					if resf1iter.Destination.AccessControlTranslation.Owner != nil {
						resf1elemf1f0.SetOwner(*resf1iter.Destination.AccessControlTranslation.Owner)
					}
					resf1elemf1.SetAccessControlTranslation(resf1elemf1f0)
				}
				if resf1iter.Destination.Account != nil {
					resf1elemf1.SetAccount(*resf1iter.Destination.Account)
				}
				if resf1iter.Destination.Bucket != nil {
					resf1elemf1.SetBucket(*resf1iter.Destination.Bucket)
				}
				if resf1iter.Destination.EncryptionConfiguration != nil {
					resf1elemf1f3 := &svcsdk.EncryptionConfiguration{}
					if resf1iter.Destination.EncryptionConfiguration.ReplicaKMSKeyID != nil {
						resf1elemf1f3.SetReplicaKmsKeyID(*resf1iter.Destination.EncryptionConfiguration.ReplicaKMSKeyID)
					}
					resf1elemf1.SetEncryptionConfiguration(resf1elemf1f3)
				}
				if resf1iter.Destination.Metrics != nil {
					resf1elemf1f4 := &svcsdk.Metrics{}
					if resf1iter.Destination.Metrics.EventThreshold != nil {
						resf1elemf1f4f0 := &svcsdk.ReplicationTimeValue{}
						if resf1iter.Destination.Metrics.EventThreshold.Minutes != nil {
							resf1elemf1f4f0.SetMinutes(*resf1iter.Destination.Metrics.EventThreshold.Minutes)
						}
						resf1elemf1f4.SetEventThreshold(resf1elemf1f4f0)
					}
					if resf1iter.Destination.Metrics.Status != nil {
						resf1elemf1f4.SetStatus(*resf1iter.Destination.Metrics.Status)
					}
					resf1elemf1.SetMetrics(resf1elemf1f4)
				}
				if resf1iter.Destination.ReplicationTime != nil {
					resf1elemf1f5 := &svcsdk.ReplicationTime{}
					if resf1iter.Destination.ReplicationTime.Status != nil {
						resf1elemf1f5.SetStatus(*resf1iter.Destination.ReplicationTime.Status)
					}
					if resf1iter.Destination.ReplicationTime.Time != nil {
						resf1elemf1f5f1 := &svcsdk.ReplicationTimeValue{}
						if resf1iter.Destination.ReplicationTime.Time.Minutes != nil {
							resf1elemf1f5f1.SetMinutes(*resf1iter.Destination.ReplicationTime.Time.Minutes)
						}
						resf1elemf1f5.SetTime(resf1elemf1f5f1)
					}
					resf1elemf1.SetReplicationTime(resf1elemf1f5)
				}
				if resf1iter.Destination.StorageClass != nil {
					resf1elemf1.SetStorageClass(*resf1iter.Destination.StorageClass)
				}
				resf1elem.SetDestination(resf1elemf1)
			}
			if resf1iter.ExistingObjectReplication != nil {
				resf1elemf2 := &svcsdk.ExistingObjectReplication{}
				if resf1iter.ExistingObjectReplication.Status != nil {
					resf1elemf2.SetStatus(*resf1iter.ExistingObjectReplication.Status)
				}
				resf1elem.SetExistingObjectReplication(resf1elemf2)
			}
			if resf1iter.Filter != nil {
				resf1elemf3 := &svcsdk.ReplicationRuleFilter{}
				if resf1iter.Filter.And != nil {
					resf1elemf3f0 := &svcsdk.ReplicationRuleAndOperator{}
					if resf1iter.Filter.And.Prefix != nil {
						resf1elemf3f0.SetPrefix(*resf1iter.Filter.And.Prefix)
					}
					if resf1iter.Filter.And.Tags != nil {
						resf1elemf3f0f1 := []*svcsdk.Tag{}
						for _, resf1elemf3f0f1iter := range resf1iter.Filter.And.Tags {
							resf1elemf3f0f1elem := &svcsdk.Tag{}
							if resf1elemf3f0f1iter.Key != nil {
								resf1elemf3f0f1elem.SetKey(*resf1elemf3f0f1iter.Key)
							}
							if resf1elemf3f0f1iter.Value != nil {
								resf1elemf3f0f1elem.SetValue(*resf1elemf3f0f1iter.Value)
							}
							resf1elemf3f0f1 = append(resf1elemf3f0f1, resf1elemf3f0f1elem)
						}
						resf1elemf3f0.SetTags(resf1elemf3f0f1)
					}
					resf1elemf3.SetAnd(resf1elemf3f0)
				}
				if resf1iter.Filter.Prefix != nil {
					resf1elemf3.SetPrefix(*resf1iter.Filter.Prefix)
				}
				if resf1iter.Filter.Tag != nil {
					resf1elemf3f2 := &svcsdk.Tag{}
					if resf1iter.Filter.Tag.Key != nil {
						resf1elemf3f2.SetKey(*resf1iter.Filter.Tag.Key)
					}
					if resf1iter.Filter.Tag.Value != nil {
						resf1elemf3f2.SetValue(*resf1iter.Filter.Tag.Value)
					}
					resf1elemf3.SetTag(resf1elemf3f2)
				}
				resf1elem.SetFilter(resf1elemf3)
			}
			if resf1iter.ID != nil {
				resf1elem.SetID(*resf1iter.ID)
			}
			if resf1iter.Prefix != nil {
				resf1elem.SetPrefix(*resf1iter.Prefix)
			}
			if resf1iter.Priority != nil {
				resf1elem.SetPriority(*resf1iter.Priority)
			}
			if resf1iter.SourceSelectionCriteria != nil {
				resf1elemf7 := &svcsdk.SourceSelectionCriteria{}
				if resf1iter.SourceSelectionCriteria.ReplicaModifications != nil {
					resf1elemf7f0 := &svcsdk.ReplicaModifications{}
					if resf1iter.SourceSelectionCriteria.ReplicaModifications.Status != nil {
						resf1elemf7f0.SetStatus(*resf1iter.SourceSelectionCriteria.ReplicaModifications.Status)
					}
					resf1elemf7.SetReplicaModifications(resf1elemf7f0)
				}
				if resf1iter.SourceSelectionCriteria.SSEKMSEncryptedObjects != nil {
					resf1elemf7f1 := &svcsdk.SseKmsEncryptedObjects{}
					if resf1iter.SourceSelectionCriteria.SSEKMSEncryptedObjects.Status != nil {
						resf1elemf7f1.SetStatus(*resf1iter.SourceSelectionCriteria.SSEKMSEncryptedObjects.Status)
					}
					resf1elemf7.SetSseKmsEncryptedObjects(resf1elemf7f1)
				}
				resf1elem.SetSourceSelectionCriteria(resf1elemf7)
			}
			if resf1iter.Status != nil {
				resf1elem.SetStatus(*resf1iter.Status)
			}
			resf1 = append(resf1, resf1elem)
		}
		res.SetRules(resf1)
	}

	return res
}

// setResourceReplication sets the `Replication` spec field
// given the output of a `GetBucketReplication` operation.
func (rm *resourceManager) setResourceReplication(
	r *resource,
	resp *svcsdk.GetBucketReplicationOutput,
) *svcapitypes.ReplicationConfiguration {
	res := &svcapitypes.ReplicationConfiguration{}
	if resp.ReplicationConfiguration.Role != nil {
		res.Role = resp.ReplicationConfiguration.Role
	}
	if resp.ReplicationConfiguration.Rules != nil {
		resf1 := []*svcapitypes.ReplicationRule{}
		for _, resf1iter := range resp.ReplicationConfiguration.Rules {
			resf1elem := &svcapitypes.ReplicationRule{}
			if resf1iter.DeleteMarkerReplication != nil {
				resf1elemf0 := &svcapitypes.DeleteMarkerReplication{}
				if resf1iter.DeleteMarkerReplication.Status != nil {
					resf1elemf0.Status = resf1iter.DeleteMarkerReplication.Status
				}
				resf1elem.DeleteMarkerReplication = resf1elemf0
			}
			if resf1iter.Destination != nil {
				resf1elemf1 := &svcapitypes.Destination{}
				if resf1iter.Destination.AccessControlTranslation != nil {
					resf1elemf1f0 := &svcapitypes.AccessControlTranslation{}
					if resf1iter.Destination.AccessControlTranslation.Owner != nil {
						resf1elemf1f0.Owner = resf1iter.Destination.AccessControlTranslation.Owner
					}
					resf1elemf1.AccessControlTranslation = resf1elemf1f0
				}
				if resf1iter.Destination.Account != nil {
					resf1elemf1.Account = resf1iter.Destination.Account
				}
				if resf1iter.Destination.Bucket != nil {
					resf1elemf1.Bucket = resf1iter.Destination.Bucket
				}
				if resf1iter.Destination.EncryptionConfiguration != nil {
					resf1elemf1f3 := &svcapitypes.EncryptionConfiguration{}
					if resf1iter.Destination.EncryptionConfiguration.ReplicaKmsKeyID != nil {
						resf1elemf1f3.ReplicaKMSKeyID = resf1iter.Destination.EncryptionConfiguration.ReplicaKmsKeyID
					}
					resf1elemf1.EncryptionConfiguration = resf1elemf1f3
				}
				if resf1iter.Destination.Metrics != nil {
					resf1elemf1f4 := &svcapitypes.Metrics{}
					if resf1iter.Destination.Metrics.EventThreshold != nil {
						resf1elemf1f4f0 := &svcapitypes.ReplicationTimeValue{}
						if resf1iter.Destination.Metrics.EventThreshold.Minutes != nil {
							resf1elemf1f4f0.Minutes = resf1iter.Destination.Metrics.EventThreshold.Minutes
						}
						resf1elemf1f4.EventThreshold = resf1elemf1f4f0
					}
					if resf1iter.Destination.Metrics.Status != nil {
						resf1elemf1f4.Status = resf1iter.Destination.Metrics.Status
					}
					resf1elemf1.Metrics = resf1elemf1f4
				}
				if resf1iter.Destination.ReplicationTime != nil {
					resf1elemf1f5 := &svcapitypes.ReplicationTime{}
					if resf1iter.Destination.ReplicationTime.Status != nil {
						resf1elemf1f5.Status = resf1iter.Destination.ReplicationTime.Status
					}
					if resf1iter.Destination.ReplicationTime.Time != nil {
						resf1elemf1f5f1 := &svcapitypes.ReplicationTimeValue{}
						if resf1iter.Destination.ReplicationTime.Time.Minutes != nil {
							resf1elemf1f5f1.Minutes = resf1iter.Destination.ReplicationTime.Time.Minutes
						}
						resf1elemf1f5.Time = resf1elemf1f5f1
					}
					resf1elemf1.ReplicationTime = resf1elemf1f5
				}
				if resf1iter.Destination.StorageClass != nil {
					resf1elemf1.StorageClass = resf1iter.Destination.StorageClass
				}
				resf1elem.Destination = resf1elemf1
			}
			if resf1iter.ExistingObjectReplication != nil {
				resf1elemf2 := &svcapitypes.ExistingObjectReplication{}
				if resf1iter.ExistingObjectReplication.Status != nil {
					resf1elemf2.Status = resf1iter.ExistingObjectReplication.Status
				}
				resf1elem.ExistingObjectReplication = resf1elemf2
			}
			if resf1iter.Filter != nil {
				resf1elemf3 := &svcapitypes.ReplicationRuleFilter{}
				if resf1iter.Filter.And != nil {
					resf1elemf3f0 := &svcapitypes.ReplicationRuleAndOperator{}
					if resf1iter.Filter.And.Prefix != nil {
						resf1elemf3f0.Prefix = resf1iter.Filter.And.Prefix
					}
					if resf1iter.Filter.And.Tags != nil {
						resf1elemf3f0f1 := []*svcapitypes.Tag{}
						for _, resf1elemf3f0f1iter := range resf1iter.Filter.And.Tags {
							resf1elemf3f0f1elem := &svcapitypes.Tag{}
							if resf1elemf3f0f1iter.Key != nil {
								resf1elemf3f0f1elem.Key = resf1elemf3f0f1iter.Key
							}
							if resf1elemf3f0f1iter.Value != nil {
								resf1elemf3f0f1elem.Value = resf1elemf3f0f1iter.Value
							}
							resf1elemf3f0f1 = append(resf1elemf3f0f1, resf1elemf3f0f1elem)
						}
						resf1elemf3f0.Tags = resf1elemf3f0f1
					}
					resf1elemf3.And = resf1elemf3f0
				}
				if resf1iter.Filter.Prefix != nil {
					resf1elemf3.Prefix = resf1iter.Filter.Prefix
				}
				if resf1iter.Filter.Tag != nil {
					resf1elemf3f2 := &svcapitypes.Tag{}
					if resf1iter.Filter.Tag.Key != nil {
						resf1elemf3f2.Key = resf1iter.Filter.Tag.Key
					}
					if resf1iter.Filter.Tag.Value != nil {
						resf1elemf3f2.Value = resf1iter.Filter.Tag.Value
					}
					resf1elemf3.Tag = resf1elemf3f2
				}
				resf1elem.Filter = resf1elemf3
			}
			if resf1iter.ID != nil {
				resf1elem.ID = resf1iter.ID
			}
			if resf1iter.Prefix != nil {
				resf1elem.Prefix = resf1iter.Prefix
			}
			if resf1iter.Priority != nil {
				resf1elem.Priority = resf1iter.Priority
			}
			if resf1iter.SourceSelectionCriteria != nil {
				resf1elemf7 := &svcapitypes.SourceSelectionCriteria{}
				if resf1iter.SourceSelectionCriteria.ReplicaModifications != nil {
					resf1elemf7f0 := &svcapitypes.ReplicaModifications{}
					if resf1iter.SourceSelectionCriteria.ReplicaModifications.Status != nil {
						resf1elemf7f0.Status = resf1iter.SourceSelectionCriteria.ReplicaModifications.Status
					}
					resf1elemf7.ReplicaModifications = resf1elemf7f0
				}
				if resf1iter.SourceSelectionCriteria.SseKmsEncryptedObjects != nil {
					resf1elemf7f1 := &svcapitypes.SSEKMSEncryptedObjects{}
					if resf1iter.SourceSelectionCriteria.SseKmsEncryptedObjects.Status != nil {
						resf1elemf7f1.Status = resf1iter.SourceSelectionCriteria.SseKmsEncryptedObjects.Status
					}
					resf1elemf7.SSEKMSEncryptedObjects = resf1elemf7f1
				}
				resf1elem.SourceSelectionCriteria = resf1elemf7
			}
			if resf1iter.Status != nil {
				resf1elem.Status = resf1iter.Status
			}
			resf1 = append(resf1, resf1elem)
		}
		res.Rules = resf1
	}

	return res
}

// newRequestPaymentConfiguration returns a RequestPaymentConfiguration object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newRequestPaymentConfiguration(
	r *resource,
) *svcsdk.RequestPaymentConfiguration {
	res := &svcsdk.RequestPaymentConfiguration{}

	if r.ko.Spec.RequestPayment.Payer != nil {
		res.SetPayer(*r.ko.Spec.RequestPayment.Payer)
	}

	return res
}

// setResourceRequestPayment sets the `RequestPayment` spec field
// given the output of a `GetBucketRequestPayment` operation.
func (rm *resourceManager) setResourceRequestPayment(
	r *resource,
	resp *svcsdk.GetBucketRequestPaymentOutput,
) *svcapitypes.RequestPaymentConfiguration {
	res := &svcapitypes.RequestPaymentConfiguration{}
	if resp.Payer != nil {
		res.Payer = resp.Payer
	}

	return res
}

// newTagging returns a Tagging object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newTagging(
	r *resource,
) *svcsdk.Tagging {
	res := &svcsdk.Tagging{}

	if r.ko.Spec.Tagging.TagSet != nil {
		resf0 := []*svcsdk.Tag{}
		for _, resf0iter := range r.ko.Spec.Tagging.TagSet {
			resf0elem := &svcsdk.Tag{}
			if resf0iter.Key != nil {
				resf0elem.SetKey(*resf0iter.Key)
			}
			if resf0iter.Value != nil {
				resf0elem.SetValue(*resf0iter.Value)
			}
			resf0 = append(resf0, resf0elem)
		}
		res.SetTagSet(resf0)
	}

	return res
}

// setResourceTagging sets the `Tagging` spec field
// given the output of a `GetBucketTagging` operation.
func (rm *resourceManager) setResourceTagging(
	r *resource,
	resp *svcsdk.GetBucketTaggingOutput,
) *svcapitypes.Tagging {
	res := &svcapitypes.Tagging{}
	if resp.TagSet != nil {
		resf0 := []*svcapitypes.Tag{}
		for _, resf0iter := range resp.TagSet {
			resf0elem := &svcapitypes.Tag{}
			if resf0iter.Key != nil {
				resf0elem.Key = resf0iter.Key
			}
			if resf0iter.Value != nil {
				resf0elem.Value = resf0iter.Value
			}
			resf0 = append(resf0, resf0elem)
		}
		res.TagSet = resf0
	}

	return res
}

// newVersioningConfiguration returns a VersioningConfiguration object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newVersioningConfiguration(
	r *resource,
) *svcsdk.VersioningConfiguration {
	res := &svcsdk.VersioningConfiguration{}

	if r.ko.Spec.Versioning.Status != nil {
		res.SetStatus(*r.ko.Spec.Versioning.Status)
	}

	return res
}

// setResourceVersioning sets the `Versioning` spec field
// given the output of a `GetBucketVersioning` operation.
func (rm *resourceManager) setResourceVersioning(
	r *resource,
	resp *svcsdk.GetBucketVersioningOutput,
) *svcapitypes.VersioningConfiguration {
	res := &svcapitypes.VersioningConfiguration{}
	if resp.Status != nil {
		res.Status = resp.Status
	}

	return res
}

// newWebsiteConfiguration returns a WebsiteConfiguration object
// with each the field set by the resource's corresponding spec field.
func (rm *resourceManager) newWebsiteConfiguration(
	r *resource,
) *svcsdk.WebsiteConfiguration {
	res := &svcsdk.WebsiteConfiguration{}

	if r.ko.Spec.Website.ErrorDocument != nil {
		resf0 := &svcsdk.ErrorDocument{}
		if r.ko.Spec.Website.ErrorDocument.Key != nil {
			resf0.SetKey(*r.ko.Spec.Website.ErrorDocument.Key)
		}
		res.SetErrorDocument(resf0)
	}
	if r.ko.Spec.Website.IndexDocument != nil {
		resf1 := &svcsdk.IndexDocument{}
		if r.ko.Spec.Website.IndexDocument.Suffix != nil {
			resf1.SetSuffix(*r.ko.Spec.Website.IndexDocument.Suffix)
		}
		res.SetIndexDocument(resf1)
	}
	if r.ko.Spec.Website.RedirectAllRequestsTo != nil {
		resf2 := &svcsdk.RedirectAllRequestsTo{}
		if r.ko.Spec.Website.RedirectAllRequestsTo.HostName != nil {
			resf2.SetHostName(*r.ko.Spec.Website.RedirectAllRequestsTo.HostName)
		}
		if r.ko.Spec.Website.RedirectAllRequestsTo.Protocol != nil {
			resf2.SetProtocol(*r.ko.Spec.Website.RedirectAllRequestsTo.Protocol)
		}
		res.SetRedirectAllRequestsTo(resf2)
	}
	if r.ko.Spec.Website.RoutingRules != nil {
		resf3 := []*svcsdk.RoutingRule{}
		for _, resf3iter := range r.ko.Spec.Website.RoutingRules {
			resf3elem := &svcsdk.RoutingRule{}
			if resf3iter.Condition != nil {
				resf3elemf0 := &svcsdk.Condition{}
				if resf3iter.Condition.HTTPErrorCodeReturnedEquals != nil {
					resf3elemf0.SetHttpErrorCodeReturnedEquals(*resf3iter.Condition.HTTPErrorCodeReturnedEquals)
				}
				if resf3iter.Condition.KeyPrefixEquals != nil {
					resf3elemf0.SetKeyPrefixEquals(*resf3iter.Condition.KeyPrefixEquals)
				}
				resf3elem.SetCondition(resf3elemf0)
			}
			if resf3iter.Redirect != nil {
				resf3elemf1 := &svcsdk.Redirect{}
				if resf3iter.Redirect.HostName != nil {
					resf3elemf1.SetHostName(*resf3iter.Redirect.HostName)
				}
				if resf3iter.Redirect.HTTPRedirectCode != nil {
					resf3elemf1.SetHttpRedirectCode(*resf3iter.Redirect.HTTPRedirectCode)
				}
				if resf3iter.Redirect.Protocol != nil {
					resf3elemf1.SetProtocol(*resf3iter.Redirect.Protocol)
				}
				if resf3iter.Redirect.ReplaceKeyPrefixWith != nil {
					resf3elemf1.SetReplaceKeyPrefixWith(*resf3iter.Redirect.ReplaceKeyPrefixWith)
				}
				if resf3iter.Redirect.ReplaceKeyWith != nil {
					resf3elemf1.SetReplaceKeyWith(*resf3iter.Redirect.ReplaceKeyWith)
				}
				resf3elem.SetRedirect(resf3elemf1)
			}
			resf3 = append(resf3, resf3elem)
		}
		res.SetRoutingRules(resf3)
	}

	return res
}

// setResourceWebsite sets the `Website` spec field
// given the output of a `GetBucketWebsite` operation.
func (rm *resourceManager) setResourceWebsite(
	r *resource,
	resp *svcsdk.GetBucketWebsiteOutput,
) *svcapitypes.WebsiteConfiguration {
	res := &svcapitypes.WebsiteConfiguration{}
	if resp.ErrorDocument != nil {
		resf0 := &svcapitypes.ErrorDocument{}
		if resp.ErrorDocument.Key != nil {
			resf0.Key = resp.ErrorDocument.Key
		}
		res.ErrorDocument = resf0
	}
	if resp.IndexDocument != nil {
		resf1 := &svcapitypes.IndexDocument{}
		if resp.IndexDocument.Suffix != nil {
			resf1.Suffix = resp.IndexDocument.Suffix
		}
		res.IndexDocument = resf1
	}
	if resp.RedirectAllRequestsTo != nil {
		resf2 := &svcapitypes.RedirectAllRequestsTo{}
		if resp.RedirectAllRequestsTo.HostName != nil {
			resf2.HostName = resp.RedirectAllRequestsTo.HostName
		}
		if resp.RedirectAllRequestsTo.Protocol != nil {
			resf2.Protocol = resp.RedirectAllRequestsTo.Protocol
		}
		res.RedirectAllRequestsTo = resf2
	}
	if resp.RoutingRules != nil {
		resf3 := []*svcapitypes.RoutingRule{}
		for _, resf3iter := range resp.RoutingRules {
			resf3elem := &svcapitypes.RoutingRule{}
			if resf3iter.Condition != nil {
				resf3elemf0 := &svcapitypes.Condition{}
				if resf3iter.Condition.HttpErrorCodeReturnedEquals != nil {
					resf3elemf0.HTTPErrorCodeReturnedEquals = resf3iter.Condition.HttpErrorCodeReturnedEquals
				}
				if resf3iter.Condition.KeyPrefixEquals != nil {
					resf3elemf0.KeyPrefixEquals = resf3iter.Condition.KeyPrefixEquals
				}
				resf3elem.Condition = resf3elemf0
			}
			if resf3iter.Redirect != nil {
				resf3elemf1 := &svcapitypes.Redirect{}
				if resf3iter.Redirect.HostName != nil {
					resf3elemf1.HostName = resf3iter.Redirect.HostName
				}
				if resf3iter.Redirect.HttpRedirectCode != nil {
					resf3elemf1.HTTPRedirectCode = resf3iter.Redirect.HttpRedirectCode
				}
				if resf3iter.Redirect.Protocol != nil {
					resf3elemf1.Protocol = resf3iter.Redirect.Protocol
				}
				if resf3iter.Redirect.ReplaceKeyPrefixWith != nil {
					resf3elemf1.ReplaceKeyPrefixWith = resf3iter.Redirect.ReplaceKeyPrefixWith
				}
				if resf3iter.Redirect.ReplaceKeyWith != nil {
					resf3elemf1.ReplaceKeyWith = resf3iter.Redirect.ReplaceKeyWith
				}
				resf3elem.Redirect = resf3elemf1
			}
			resf3 = append(resf3, resf3elem)
		}
		res.RoutingRules = resf3
	}

	return res
}
