apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ack-s3-controller.app.fullname" . }}-namespace-caches
  labels:
    {{- include "ack-s3-controller.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "ack-s3-controller.app.fullname" . }}-namespace-caches
subjects:
- kind: ServiceAccount
  name: {{ include "ack-s3-controller.service-account.name" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ack-s3-controller.app.fullname" . }}-configmaps-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ack-s3-controller.labels" . | nindent 4 }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "ack-s3-controller.app.fullname" . }}-configmaps-cache
subjects:
- kind: ServiceAccount
  name: {{ include "ack-s3-controller.service-account.name" . }}
  namespace: {{ .Release.Namespace }}
