apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ack-s3-controller.app.fullname" . }}-namespaces-cache
  labels:
    {{- include "ack-s3-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ack-s3-controller.app.fullname" . }}-configmaps-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ack-s3-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
