{{ if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ack-s3-controller.app.fullname" . }}-leaderelection
{{ if .Values.leaderElection.namespace }}
  namespace: {{ .Values.leaderElection.namespace }}
{{ else }}
  namespace: {{ .Release.Namespace }}
{{ end }}
  labels:
    {{- include "ack-s3-controller.labels" $ | nindent 4 }}
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ack-s3-controller.app.fullname" . }}-leaderelection
subjects:
- kind: ServiceAccount
  name: {{ include "ack-s3-controller.service-account.name" . }}
  namespace: {{ .Release.Namespace }}{{- end }}
