---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "ack-s3-controller.app.fullname" . }}-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ack-s3-controller.labels" $ | nindent 4 }}
rules:
- apiGroups:
  - s3.services.k8s.aws
  resources:
  - buckets
  verbs:
  - get
  - list
  - watch
