// Code generated by ack-generate. DO NOT EDIT.
// This file is regenerated on each run of `ack-generate e2e-tests`.

package e2e

import (
	"context"
	"log"
	"os"
	"testing"

	"github.com/aws/aws-sdk-go-v2/config"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/s3"
	"k8s.io/apimachinery/pkg/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"

	svcapitypes "github.com/aws-controllers-k8s/s3-controller/apis/v1alpha1"
	acktest "github.com/aws-controllers-k8s/test-infra/pkg/e2e"
)

var awsClient *svcsdk.Client

func TestMain(m *testing.M) {
	scheme := runtime.NewScheme()
	_ = clientgoscheme.AddToScheme(scheme)
	_ = svcapitypes.AddToScheme(scheme)

	acktest.SetScheme(scheme)
	acktest.Setup()

	ctx := context.Background()
	awsCfg, err := config.LoadDefaultConfig(ctx)
	if err != nil {
		log.Fatalf("failed to load AWS config: %v", err)
	}
	awsClient = svcsdk.NewFromConfig(awsCfg)

	code := m.Run()

	acktest.Teardown()
	os.Exit(code)
}
