// Code generated by ack-generate. DO NOT EDIT.
// This file is regenerated on each run of `ack-generate e2e-tests`.

package e2e

import (
	"context"
	"testing"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/s3"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/s3/types"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/s3-controller/apis/v1alpha1"
	acktest "github.com/aws-controllers-k8s/test-infra/pkg/e2e"
)

// Ensure imports are used.
var (
	_ = aws.String
	_ = svcsdk.New
	_ = svcsdktypes.NoSuchBucket{}
)

func TestBucket_Accelerate(t *testing.T) {
	// t.Parallel()
	ctx := context.Background()
	name := acktest.RandomName("bucket", 40)

	t.Logf("test starting for Bucket with name %s", name)

	resource := &svcapitypes.Bucket{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: acktest.Namespace(),
		},
		Spec: svcapitypes.BucketSpec{
			Accelerate: &svcapitypes.AccelerateConfiguration{Status: new("Enabled")},
			Name:       &name,
		},
	}

	// Create
	t.Logf("  Accelerate: %s", acktest.FormatVal(resource.Spec.Accelerate))
	t.Logf("  Name: %s", acktest.FormatVal(resource.Spec.Name))
	t.Logf("creating Bucket %s in namespace %s", name, acktest.Namespace())
	createStart := time.Now()
	err := acktest.CreateResource(ctx, resource)
	require.NoError(t, err, "failed to create Bucket")
	t.Logf("Bucket %s created successfully (took %s)", name, time.Since(createStart))
	t.Cleanup(func() {
		t.Logf("deleting Bucket %s", name)
		deleteStart := time.Now()
		if err := acktest.DeleteResource(context.Background(), resource); err != nil {
			t.Logf("warning: failed to delete Bucket %s: %v", name, err)
		} else {
			t.Logf("Bucket %s deleted (took %s)", name, time.Since(deleteStart))
		}
	})

	// Wait for sync
	t.Logf("waiting for Bucket %s to become synced (timeout: 30*time.Second)", name)
	syncStart := time.Now()
	err = acktest.WaitForCondition(ctx, resource, "ACK.ResourceSynced", "True", 30*time.Second)
	require.NoError(t, err, "Bucket did not become synced")
	t.Logf("Bucket %s synced (took %s)", name, time.Since(syncStart))

	// Verify in AWS after create
	t.Logf("verifying Bucket %s in AWS...", name)
	{
		resp, err := awsClient.GetBucketAccelerateConfiguration(ctx, &svcsdk.GetBucketAccelerateConfigurationInput{
			Bucket: aws.String(name),
		})
		require.NoError(t, err, "GetBucketAccelerateConfiguration failed")
		require.Equal(t, svcsdktypes.BucketAccelerateStatus("Enabled"), resp.Status, "Accelerate.Status mismatch")
	}
	t.Logf("AWS verification passed for Bucket %s", name)

	// Update
	err = acktest.GetResource(ctx, resource)
	require.NoError(t, err, "failed to get Bucket before update")
	updated := resource.DeepCopy()
	updated.Spec.Accelerate = &svcapitypes.AccelerateConfiguration{Status: new("Suspended")}
	t.Logf("updating Bucket %s:", name)
	t.Logf("  Accelerate: %s", acktest.FormatVal(updated.Spec.Accelerate))
	updateStart := time.Now()
	err = acktest.UpdateResource(ctx, updated)
	require.NoError(t, err, "failed to update Bucket")
	t.Logf("Bucket %s update applied (took %s)", name, time.Since(updateStart))

	time.Sleep(5 * time.Second)

	t.Logf("waiting for Bucket %s to re-sync after update (timeout: 30*time.Second)", name)
	resyncStart := time.Now()
	err = acktest.WaitForCondition(ctx, updated, "ACK.ResourceSynced", "True", 30*time.Second)
	require.NoError(t, err, "Bucket did not re-sync after update")
	t.Logf("Bucket %s re-synced after update (took %s)", name, time.Since(resyncStart))

	// Verify in AWS after update
	t.Logf("verifying Bucket %s in AWS after update...", name)
	{
		resp, err := awsClient.GetBucketAccelerateConfiguration(ctx, &svcsdk.GetBucketAccelerateConfigurationInput{
			Bucket: aws.String(name),
		})
		require.NoError(t, err, "GetBucketAccelerateConfiguration failed after update")
		require.Equal(t, svcsdktypes.BucketAccelerateStatus("Suspended"), resp.Status, "Accelerate.Status mismatch")
	}
	t.Logf("AWS verification after update passed for Bucket %s", name)

}

func TestBucket_PublicAccessBlock(t *testing.T) {
	// t.Parallel()
	ctx := context.Background()
	name := acktest.RandomName("bucket", 40)

	t.Logf("test starting for Bucket with name %s", name)

	resource := &svcapitypes.Bucket{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: acktest.Namespace(),
		},
		Spec: svcapitypes.BucketSpec{
			Name: &name,
			PublicAccessBlock: &svcapitypes.PublicAccessBlockConfiguration{
				BlockPublicPolicy:     new(bool(true)),
				RestrictPublicBuckets: new(bool(true)),
				BlockPublicACLs:       new(bool(true)),
				IgnorePublicACLs:      new(bool(true)),
			},
		},
	}

	// Create
	t.Logf("  Name: %s", acktest.FormatVal(resource.Spec.Name))
	t.Logf("  PublicAccessBlock: %s", acktest.FormatVal(resource.Spec.PublicAccessBlock))
	t.Logf("creating Bucket %s in namespace %s", name, acktest.Namespace())
	createStart := time.Now()
	err := acktest.CreateResource(ctx, resource)
	require.NoError(t, err, "failed to create Bucket")
	t.Logf("Bucket %s created successfully (took %s)", name, time.Since(createStart))
	t.Cleanup(func() {
		t.Logf("deleting Bucket %s", name)
		deleteStart := time.Now()
		if err := acktest.DeleteResource(context.Background(), resource); err != nil {
			t.Logf("warning: failed to delete Bucket %s: %v", name, err)
		} else {
			t.Logf("Bucket %s deleted (took %s)", name, time.Since(deleteStart))
		}
	})

	// Wait for sync
	t.Logf("waiting for Bucket %s to become synced (timeout: 30*time.Second)", name)
	syncStart := time.Now()
	err = acktest.WaitForCondition(ctx, resource, "ACK.ResourceSynced", "True", 30*time.Second)
	require.NoError(t, err, "Bucket did not become synced")
	t.Logf("Bucket %s synced (took %s)", name, time.Since(syncStart))

	// Verify in AWS after create
	t.Logf("verifying Bucket %s in AWS...", name)
	{
		resp, err := awsClient.GetPublicAccessBlock(ctx, &svcsdk.GetPublicAccessBlockInput{
			Bucket: aws.String(name),
		})
		require.NoError(t, err, "GetPublicAccessBlock failed")
		require.Equal(t, true, aws.ToBool(resp.PublicAccessBlockConfiguration.BlockPublicAcls), "PublicAccessBlock.BlockPublicACLs mismatch")
		require.Equal(t, true, aws.ToBool(resp.PublicAccessBlockConfiguration.BlockPublicPolicy), "PublicAccessBlock.BlockPublicPolicy mismatch")
		require.Equal(t, true, aws.ToBool(resp.PublicAccessBlockConfiguration.IgnorePublicAcls), "PublicAccessBlock.IgnorePublicACLs mismatch")
		require.Equal(t, true, aws.ToBool(resp.PublicAccessBlockConfiguration.RestrictPublicBuckets), "PublicAccessBlock.RestrictPublicBuckets mismatch")
	}
	t.Logf("AWS verification passed for Bucket %s", name)

	// Update
	err = acktest.GetResource(ctx, resource)
	require.NoError(t, err, "failed to get Bucket before update")
	updated := resource.DeepCopy()
	updated.Spec.PublicAccessBlock = &svcapitypes.PublicAccessBlockConfiguration{
		BlockPublicACLs:       new(bool(false)),
		IgnorePublicACLs:      new(bool(false)),
		BlockPublicPolicy:     new(bool(false)),
		RestrictPublicBuckets: new(bool(false)),
	}
	t.Logf("updating Bucket %s:", name)
	t.Logf("  PublicAccessBlock: %s", acktest.FormatVal(updated.Spec.PublicAccessBlock))
	updateStart := time.Now()
	err = acktest.UpdateResource(ctx, updated)
	require.NoError(t, err, "failed to update Bucket")
	t.Logf("Bucket %s update applied (took %s)", name, time.Since(updateStart))

	time.Sleep(5 * time.Second)

	t.Logf("waiting for Bucket %s to re-sync after update (timeout: 30*time.Second)", name)
	resyncStart := time.Now()
	err = acktest.WaitForCondition(ctx, updated, "ACK.ResourceSynced", "True", 30*time.Second)
	require.NoError(t, err, "Bucket did not re-sync after update")
	t.Logf("Bucket %s re-synced after update (took %s)", name, time.Since(resyncStart))

	// Verify in AWS after update
	t.Logf("verifying Bucket %s in AWS after update...", name)
	{
		resp, err := awsClient.GetPublicAccessBlock(ctx, &svcsdk.GetPublicAccessBlockInput{
			Bucket: aws.String(name),
		})
		require.NoError(t, err, "GetPublicAccessBlock failed after update")
		require.Equal(t, false, aws.ToBool(resp.PublicAccessBlockConfiguration.BlockPublicAcls), "PublicAccessBlock.BlockPublicACLs mismatch")
		require.Equal(t, false, aws.ToBool(resp.PublicAccessBlockConfiguration.BlockPublicPolicy), "PublicAccessBlock.BlockPublicPolicy mismatch")
		require.Equal(t, false, aws.ToBool(resp.PublicAccessBlockConfiguration.IgnorePublicAcls), "PublicAccessBlock.IgnorePublicACLs mismatch")
		require.Equal(t, false, aws.ToBool(resp.PublicAccessBlockConfiguration.RestrictPublicBuckets), "PublicAccessBlock.RestrictPublicBuckets mismatch")
	}
	t.Logf("AWS verification after update passed for Bucket %s", name)

}

func TestBucket_RequestPayment(t *testing.T) {
	// t.Parallel()
	ctx := context.Background()
	name := acktest.RandomName("bucket", 40)

	t.Logf("test starting for Bucket with name %s", name)

	resource := &svcapitypes.Bucket{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: acktest.Namespace(),
		},
		Spec: svcapitypes.BucketSpec{
			Name:           &name,
			RequestPayment: &svcapitypes.RequestPaymentConfiguration{Payer: new("Requester")},
		},
	}

	// Create
	t.Logf("  Name: %s", acktest.FormatVal(resource.Spec.Name))
	t.Logf("  RequestPayment: %s", acktest.FormatVal(resource.Spec.RequestPayment))
	t.Logf("creating Bucket %s in namespace %s", name, acktest.Namespace())
	createStart := time.Now()
	err := acktest.CreateResource(ctx, resource)
	require.NoError(t, err, "failed to create Bucket")
	t.Logf("Bucket %s created successfully (took %s)", name, time.Since(createStart))
	t.Cleanup(func() {
		t.Logf("deleting Bucket %s", name)
		deleteStart := time.Now()
		if err := acktest.DeleteResource(context.Background(), resource); err != nil {
			t.Logf("warning: failed to delete Bucket %s: %v", name, err)
		} else {
			t.Logf("Bucket %s deleted (took %s)", name, time.Since(deleteStart))
		}
	})

	// Wait for sync
	t.Logf("waiting for Bucket %s to become synced (timeout: 30*time.Second)", name)
	syncStart := time.Now()
	err = acktest.WaitForCondition(ctx, resource, "ACK.ResourceSynced", "True", 30*time.Second)
	require.NoError(t, err, "Bucket did not become synced")
	t.Logf("Bucket %s synced (took %s)", name, time.Since(syncStart))

	// Verify in AWS after create
	t.Logf("verifying Bucket %s in AWS...", name)
	{
		resp, err := awsClient.GetBucketRequestPayment(ctx, &svcsdk.GetBucketRequestPaymentInput{
			Bucket: aws.String(name),
		})
		require.NoError(t, err, "GetBucketRequestPayment failed")
		require.Equal(t, svcsdktypes.Payer("Requester"), resp.Payer, "RequestPayment.Payer mismatch")
	}
	t.Logf("AWS verification passed for Bucket %s", name)

	// Update
	err = acktest.GetResource(ctx, resource)
	require.NoError(t, err, "failed to get Bucket before update")
	updated := resource.DeepCopy()
	updated.Spec.RequestPayment = &svcapitypes.RequestPaymentConfiguration{Payer: new("BucketOwner")}
	t.Logf("updating Bucket %s:", name)
	t.Logf("  RequestPayment: %s", acktest.FormatVal(updated.Spec.RequestPayment))
	updateStart := time.Now()
	err = acktest.UpdateResource(ctx, updated)
	require.NoError(t, err, "failed to update Bucket")
	t.Logf("Bucket %s update applied (took %s)", name, time.Since(updateStart))

	time.Sleep(5 * time.Second)

	t.Logf("waiting for Bucket %s to re-sync after update (timeout: 30*time.Second)", name)
	resyncStart := time.Now()
	err = acktest.WaitForCondition(ctx, updated, "ACK.ResourceSynced", "True", 30*time.Second)
	require.NoError(t, err, "Bucket did not re-sync after update")
	t.Logf("Bucket %s re-synced after update (took %s)", name, time.Since(resyncStart))

	// Verify in AWS after update
	t.Logf("verifying Bucket %s in AWS after update...", name)
	{
		resp, err := awsClient.GetBucketRequestPayment(ctx, &svcsdk.GetBucketRequestPaymentInput{
			Bucket: aws.String(name),
		})
		require.NoError(t, err, "GetBucketRequestPayment failed after update")
		require.Equal(t, svcsdktypes.Payer("BucketOwner"), resp.Payer, "RequestPayment.Payer mismatch")
	}
	t.Logf("AWS verification after update passed for Bucket %s", name)

}

func TestBucket_VersioningLifecycle(t *testing.T) {
	// t.Parallel()
	ctx := context.Background()
	name := acktest.RandomName("bucket", 40)

	t.Logf("test starting for Bucket with name %s", name)

	resource := &svcapitypes.Bucket{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: acktest.Namespace(),
		},
		Spec: svcapitypes.BucketSpec{
			Name:       &name,
			Versioning: &svcapitypes.VersioningConfiguration{Status: new("Enabled")},
		},
	}

	// Create
	t.Logf("  Name: %s", acktest.FormatVal(resource.Spec.Name))
	t.Logf("  Versioning: %s", acktest.FormatVal(resource.Spec.Versioning))
	t.Logf("creating Bucket %s in namespace %s", name, acktest.Namespace())
	createStart := time.Now()
	err := acktest.CreateResource(ctx, resource)
	require.NoError(t, err, "failed to create Bucket")
	t.Logf("Bucket %s created successfully (took %s)", name, time.Since(createStart))
	t.Cleanup(func() {
		t.Logf("deleting Bucket %s", name)
		deleteStart := time.Now()
		if err := acktest.DeleteResource(context.Background(), resource); err != nil {
			t.Logf("warning: failed to delete Bucket %s: %v", name, err)
		} else {
			t.Logf("Bucket %s deleted (took %s)", name, time.Since(deleteStart))
		}
	})

	// Wait for sync
	t.Logf("waiting for Bucket %s to become synced (timeout: 30*time.Second)", name)
	syncStart := time.Now()
	err = acktest.WaitForCondition(ctx, resource, "ACK.ResourceSynced", "True", 30*time.Second)
	require.NoError(t, err, "Bucket did not become synced")
	t.Logf("Bucket %s synced (took %s)", name, time.Since(syncStart))

	// Verify in AWS after create
	t.Logf("verifying Bucket %s in AWS...", name)
	{
		resp, err := awsClient.GetBucketVersioning(ctx, &svcsdk.GetBucketVersioningInput{
			Bucket: aws.String(name),
		})
		require.NoError(t, err, "GetBucketVersioning failed")
		require.Equal(t, svcsdktypes.BucketVersioningStatus("Enabled"), resp.Status, "Versioning.Status mismatch")
	}
	t.Logf("AWS verification passed for Bucket %s", name)

	// Update
	err = acktest.GetResource(ctx, resource)
	require.NoError(t, err, "failed to get Bucket before update")
	updated := resource.DeepCopy()
	updated.Spec.Versioning = &svcapitypes.VersioningConfiguration{Status: new("Suspended")}
	t.Logf("updating Bucket %s:", name)
	t.Logf("  Versioning: %s", acktest.FormatVal(updated.Spec.Versioning))
	updateStart := time.Now()
	err = acktest.UpdateResource(ctx, updated)
	require.NoError(t, err, "failed to update Bucket")
	t.Logf("Bucket %s update applied (took %s)", name, time.Since(updateStart))

	time.Sleep(5 * time.Second)

	t.Logf("waiting for Bucket %s to re-sync after update (timeout: 30*time.Second)", name)
	resyncStart := time.Now()
	err = acktest.WaitForCondition(ctx, updated, "ACK.ResourceSynced", "True", 30*time.Second)
	require.NoError(t, err, "Bucket did not re-sync after update")
	t.Logf("Bucket %s re-synced after update (took %s)", name, time.Since(resyncStart))

	// Verify in AWS after update
	t.Logf("verifying Bucket %s in AWS after update...", name)
	{
		resp, err := awsClient.GetBucketVersioning(ctx, &svcsdk.GetBucketVersioningInput{
			Bucket: aws.String(name),
		})
		require.NoError(t, err, "GetBucketVersioning failed after update")
		require.Equal(t, svcsdktypes.BucketVersioningStatus("Suspended"), resp.Status, "Versioning.Status mismatch")
	}
	t.Logf("AWS verification after update passed for Bucket %s", name)

}
